In [7]:
import pandas as pd 
df_10k  = pd.read_csv('acc_data_sampling_50.csv', engine = "python")

In [21]:
df_fatalk  = pd.read_csv('acc_data_after_cleaning.csv', engine = "python")

In [22]:
df_fatalk.shape

(186050, 62)

In [26]:
df_slight1=df_fatalk.query('accident_severity == 3').head(3570)
df_slight1

,vehicle_type,towing_and_articulation,vehicle_manoeuvre,vehicle_location-restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,1st_point_of_impact,...,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_home_area_type,casualty_imd_decile
0,9,0,18,0,8,0,0,0,0,1,...,8,3,0,0,0,0,0,9,1,3
1,20,0,4,0,0,0,0,0,0,1,...,6,3,1,1,0,0,0,0,1,1
2,1,0,9,0,5,0,0,0,0,1,...,8,3,0,0,0,0,0,1,1,2
3,3,0,4,0,2,0,0,0,0,1,...,6,3,0,0,0,0,0,3,1,3
4,9,0,14,0,1,0,0,0,0,4,...,3,3,1,2,0,0,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4143,1,0,18,0,8,0,0,0,0,1,...,6,3,0,0,0,0,0,1,1,3
4144,1,0,9,0,8,0,0,0,0,1,...,6,3,0,0,0,0,0,1,1,5
4146,1,0,9,0,8,0,0,0,0,3,...,7,3,0,0,0,0,0,1,3,5
4147,1,0,17,0,0,0,4,0,0,1,...,6,3,0,0,0,0,0,1,1,5
4148,3,0,9,0,8,0,10,3,4,1,...,4,3,0,0,0,0,0,3,1,3

In [27]:
df_fatalk['accident_severity'].value_counts()

3    155053
2     28161
1      2836
Name: accident_severity, dtype: int64

In [28]:
df_slight1=df_fatalk.query('accident_severity == 3').head(3750)
df_serious1=df_fatalk.query('accident_severity == 2').head(3750)
df_fatal1 = df_fatalk.query('accident_severity == 1')

In [12]:
df_slight1=df_10k.query('accident_severity == 3')

In [29]:
df_fatal1.shape

(2836, 62)

In [31]:
df_serious_fatal = df_serious1.append(df_fatal1, ignore_index = True)
dff_10k=df_serious_fatal.append(df_slight1,ignore_index=True)

In [32]:
dff_10k.shape

(10336, 62)

In [33]:
dff_10k['accident_severity'].value_counts()

2    3750
3    3750
1    2836
Name: accident_severity, dtype: int64

In [35]:
dff_10k

,vehicle_type,towing_and_articulation,vehicle_manoeuvre,vehicle_location-restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,1st_point_of_impact,...,age_band_of_casualty,casualty_severity,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_home_area_type,casualty_imd_decile
0,9,0,16,0,0,1,0,7,10,3,...,6,2,0,0,0,0,0,9,1,1
1,1,0,18,0,8,0,0,0,0,2,...,6,2,0,0,0,0,0,1,1,1
2,1,0,18,0,8,0,0,0,0,1,...,6,2,0,0,0,0,0,1,1,5
3,9,0,18,0,4,0,10,3,4,1,...,6,2,0,0,0,0,0,9,1,5
4,5,0,13,0,8,0,0,0,0,1,...,8,2,0,0,0,0,0,5,3,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10331,3,0,18,0,8,0,0,0,0,3,...,7,3,0,0,0,0,0,3,1,6
10332,8,0,18,0,8,0,0,0,0,1,...,4,3,1,1,0,0,2,0,1,3
10333,1,0,18,0,0,0,0,0,0,1,...,9,3,4,1,0,0,2,0,1,5
10334,1,0,17,0,0,0,0,0,0,1,...,7,3,0,0,0,0,0,1,1,7
10335,2,0,18,0,0,0,0,0,0,1,...,4,3,0,0,0,0,0,2,1,3

col

new_col = w['vehicle_type', 'towing_and_articulation', 'vehicle_manoeuvre',
       'vehicle_location-restricted_lane', 
       'skidding_and_overturning', 'hit_object_in_carriageway',
       'vehicle_leaving_carriageway', 'hit_object_off_carriageway',
       '1st_point_of_impact', 
       'journey_purpose_of_driver', 'sex_of_driver', 'age_of_driver',
       'age_band_of_driver', 'engine_capacity_(cc)', 'propulsion_code',
       'age_of_vehicle',
       'NUmber_of_Casualities_unique_to_accident_index',
       'No_of_Vehicles_involved_unique_to_accident_index', 'accident_severity', 'number_of_vehicles',
       'number_of_casualties', 'day_of_week', 'time',
       '1st_road_class', '1st_road_number', 'road_type', 'speed_limit',
       'junction_detail', 'junction_control', '2nd_road_class',
       '2nd_road_number', 'pedestrian_crossing-human_control',
       'pedestrian_crossing-physical_facilities', 'light_conditions',
       'weather_conditions', 'road_surface_conditions',
       'special_conditions_at_site', 'carriageway_hazards',
       'urban_or_rural_area', 'casualty_class', 'sex_of_casualty',
       'age_of_casualty', 'age_band_of_casualty', 'casualty_severity',
       'pedestrian_location', 'pedestrian_movement', 'car_passenger',
       'bus_or_coach_passenger', 'pedestrian_road_maintenance_worker',
       'casualty_type']

len(new_col)

cols_not_in_dataset = set(data.columns) -  set(new_col)

for col in cols_not_in_dataset:
    print(col)

In [5]:
dff_10k

,vehicle_type,towing_and_articulation,vehicle_manoeuvre,vehicle_location-restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,1st_point_of_impact,...,age_band_of_casualty,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type,casualty_home_area_type,casualty_imd_decile,casualty_severity
0,1,0,18,0,0,0,0,0,0,3,...,9,0,0,0,0,0,1,3,4,2
1,9,0,17,0,0,1,10,8,0,3,...,4,0,0,0,0,0,9,1,5,2
2,9,0,18,0,2,1,0,0,0,1,...,6,0,0,1,0,0,9,1,5,2
3,4,0,17,0,0,0,0,0,0,3,...,8,0,0,0,0,0,4,2,9,2
4,9,0,9,0,6,0,0,0,0,1,...,11,5,1,0,0,0,0,2,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46204,9,0,18,0,3,0,0,1,0,1,...,9,5,3,0,0,0,0,1,1,3
46205,9,0,15,0,0,5,0,1,4,3,...,8,0,0,0,0,0,9,1,2,3
46206,9,0,18,0,0,2,0,1,11,1,...,4,0,0,1,0,0,9,1,1,2
46207,9,0,18,0,0,0,0,0,0,1,...,6,0,0,0,0,0,9,1,3,1
46208,1,0,7,0,6,0,0,0,0,1,...,5,0,0,0,0,0,1,2,5,3

In [37]:
dff_10k.to_csv("dff_10k.csv",index = False)