In [1]:
import pandas as pd 
data_process  = pd.read_csv('dff_10k.csv', engine = "python")

In [2]:


new_col = ['vehicle_type', 'towing_and_articulation', 'vehicle_manoeuvre', 'vehicle_location-restricted_lane', 'skidding_and_overturning', 'hit_object_in_carriageway', 'vehicle_leaving_carriageway', 'hit_object_off_carriageway', '1st_point_of_impact', 'journey_purpose_of_driver', 'sex_of_driver', 'age_of_driver', 'age_band_of_driver', 'engine_capacity_(cc)', 'propulsion_code', 'age_of_vehicle','No_of_Vehicles_involved_unique_to_accident_index', 'accident_severity', 'number_of_vehicles', 'number_of_casualties', 'day_of_week', 'time', '1st_road_class', '1st_road_number', 'road_type', 'speed_limit', 'junction_detail', 'junction_control', '2nd_road_class', '2nd_road_number', 'pedestrian_crossing-human_control', 'pedestrian_crossing-physical_facilities', 'light_conditions', 'weather_conditions', 'road_surface_conditions', 'special_conditions_at_site', 'carriageway_hazards', 'urban_or_rural_area', 'casualty_class', 'sex_of_casualty', 'age_of_casualty', 'age_band_of_casualty', 'pedestrian_location', 'pedestrian_movement', 'car_passenger', 'bus_or_coach_passenger', 'pedestrian_road_maintenance_worker', 'casualty_type']

In [3]:
len(new_col)

48

In [47]:
cols_not_in_dataset = set(data_process.columns) - set(new_col)

In [48]:
cols_not_in_dataset

{'NUmber_of_Casualities_unique_to_accident_index',
 'casualty_home_area_type',
 'casualty_imd_decile',
 'casualty_reference',
 'casualty_severity',
 'did_police_officer_attend_scene_of_accident',
 'driver_home_area_type',
 'junction_location',
 'latitude',
 'local_authority_(district)',
 'local_authority_(highway)',
 'longitude',
 'police_force',
 'was_vehicle_left_hand_drive?'}

In [6]:
data_process_v1 = data_process[new_col]

In [7]:
data_process_v1

,vehicle_type,towing_and_articulation,vehicle_manoeuvre,vehicle_location-restricted_lane,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,1st_point_of_impact,journey_purpose_of_driver,...,casualty_class,sex_of_casualty,age_of_casualty,age_band_of_casualty,pedestrian_location,pedestrian_movement,car_passenger,bus_or_coach_passenger,pedestrian_road_maintenance_worker,casualty_type
0,9,0,16,0,1,0,7,10,3,6,...,1,1,32,6,0,0,0,0,0,9
1,1,0,18,0,0,0,0,0,2,6,...,1,2,33,6,0,0,0,0,0,1
2,1,0,18,0,0,0,0,0,1,2,...,1,1,33,6,0,0,0,0,0,1
3,9,0,18,0,0,10,3,4,1,6,...,1,1,30,6,0,0,0,0,0,9
4,5,0,13,0,0,0,0,0,1,6,...,1,1,47,8,0,0,0,0,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10331,3,0,18,0,0,0,0,0,3,6,...,1,1,44,7,0,0,0,0,0,3
10332,8,0,18,0,0,0,0,0,1,1,...,3,2,17,4,1,1,0,0,2,0
10333,1,0,18,0,0,0,0,0,1,6,...,3,2,57,9,4,1,0,0,2,0
10334,1,0,17,0,0,0,0,0,1,6,...,1,1,44,7,0,0,0,0,0,1
10335,2,0,18,0,0,0,0,0,1,6,...,1,1,20,4,0,0,0,0,0,2

In [8]:
data_process_v1.to_csv('data_process_v1.csv',index = False)

In [52]:
data_process_v1['1st_road_number'].value_counts()

0       2733
4        231
6        193
40       185
5        154
        ...
4040       1
4540       1
418        1
417        1
6239       1
Name: 1st_road_number, Length: 1056, dtype: int64

In [53]:
new_col1 =[ 'vehicle_type', 'towing_and_articulation', 'sex_of_driver', 'age_of_driver',
       'age_band_of_driver', 'engine_capacity_(cc)', 'propulsion_code',
       'age_of_vehicle',
       'accident_severity', 'number_of_vehicles',
       'day_of_week','1st_road_class', 'road_type',
       'speed_limit', 'junction_detail', 'junction_control', '2nd_road_class',
       '2nd_road_number', 'pedestrian_crossing-human_control',
       'pedestrian_crossing-physical_facilities', 'light_conditions',
       'weather_conditions', 'road_surface_conditions',
       'special_conditions_at_site',
       'urban_or_rural_area']

In [54]:
data_process_v2 = data_process_v1[new_col1]

In [55]:
data_process_v2

,vehicle_type,towing_and_articulation,sex_of_driver,age_of_driver,age_band_of_driver,engine_capacity_(cc),propulsion_code,age_of_vehicle,accident_severity,number_of_vehicles,...,junction_control,2nd_road_class,2nd_road_number,pedestrian_crossing-human_control,pedestrian_crossing-physical_facilities,light_conditions,weather_conditions,road_surface_conditions,special_conditions_at_site,urban_or_rural_area
0,9,0,1,32,6,1396,1,11,2,1,...,0,0,0,0,0,1,1,1,0,1
1,1,0,2,33,6,1587,1,8,2,2,...,8,8,5093,0,0,1,1,1,0,1
2,1,0,1,33,6,1587,1,8,2,2,...,8,8,0,0,0,1,1,1,0,1
3,9,0,1,30,6,698,1,8,2,2,...,4,4,57,0,0,4,1,1,0,1
4,5,0,1,47,8,1585,2,6,2,2,...,8,8,0,0,0,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10331,3,0,1,44,7,124,1,13,3,2,...,8,8,0,0,5,1,1,1,0,1
10332,8,0,1,31,6,2143,2,1,3,1,...,8,8,400,0,5,1,1,1,0,1
10333,1,0,1,29,6,1587,1,8,3,1,...,0,0,0,0,5,4,1,1,0,1
10334,1,0,1,44,7,1587,1,8,3,2,...,0,0,0,0,0,1,1,1,0,1
10335,2,0,1,20,4,114,1,8,3,1,...,0,0,0,0,0,1,2,2,0,1

In [56]:
cols_not_in_dataset1 = set(data_process_v1.columns) - set(new_col1)
cols_not_in_dataset1

{'1st_point_of_impact',
 '1st_road_number',
 'No_of_Vehicles_involved_unique_to_accident_index',
 'age_band_of_casualty',
 'age_of_casualty',
 'bus_or_coach_passenger',
 'car_passenger',
 'carriageway_hazards',
 'casualty_class',
 'casualty_type',
 'hit_object_in_carriageway',
 'hit_object_off_carriageway',
 'journey_purpose_of_driver',
 'number_of_casualties',
 'pedestrian_location',
 'pedestrian_movement',
 'pedestrian_road_maintenance_worker',
 'sex_of_casualty',
 'skidding_and_overturning',
 'time',
 'vehicle_leaving_carriageway',
 'vehicle_location-restricted_lane',
 'vehicle_manoeuvre'}

In [57]:
data_process_v2.to_csv('data_process_v2.csv',index = False)